In [1]:
import numpy as np
import pandas as pd
import nltk
nltk.download(["punkt","stopwords","wordnet"])

[nltk_data] Downloading package punkt to /Users/sr7037/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/sr7037/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/sr7037/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [2]:
movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")
movies

movieId                                title  \
0            1                     Toy Story (1995)   
1            2                       Jumanji (1995)   
2            3              Grumpier Old Men (1995)   
3            4             Waiting to Exhale (1995)   
4            5   Father of the Bride Part II (1995)   
...        ...                                  ...   
10324   146684        Cosmic Scrat-tastrophe (2015)   
10325   146878           Le Grand Restaurant (1966)   
10326   148238       A Very Murray Christmas (2015)   
10327   148626                 The Big Short (2015)   
10328   149532  Marco Polo: One Hundred Eyes (2015)   

                                            genres  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
10324                    Animation|Children|Comedy  
10325                                       Comedy  
10326                                       Comedy  
10327                                        Drama  
10328                           (no genres listed)  

[10329 rows x 3 columns]

In [3]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
genres = movies["genres"]
li=[]
for i in range(len(genres)):
    temp = genres[i].lower()
    temp = temp.split("|")
    temp = [lemmatizer.lemmatize(word) for word in temp]
    li.append(" ".join(temp))

In [4]:
movies_dataset = pd.DataFrame(li,columns=["genres"],index=movies["title"])
movies_dataset

genres
title                                                                        
Toy Story (1995)                     adventure animation child comedy fantasy
Jumanji (1995)                                        adventure child fantasy
Grumpier Old Men (1995)                                        comedy romance
Waiting to Exhale (1995)                                 comedy drama romance
Father of the Bride Part II (1995)                                     comedy
...                                                                       ...
Cosmic Scrat-tastrophe (2015)                          animation child comedy
Le Grand Restaurant (1966)                                             comedy
A Very Murray Christmas (2015)                                         comedy
The Big Short (2015)                                                    drama
Marco Polo: One Hundred Eyes (2015)                        (no genres listed)

[10329 rows x 1 columns]

In [5]:
#Finding based on similar movies
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(movies_dataset["genres"]).toarray()
X

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [9]:
print("Count Vector : \n",X)
print("\nNote: First row of above count vector: ",X[0])
print("\nColumns Coresponding to above count vector is :\n",cv.get_feature_names())

Count Vector : 
 [[0 1 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Note: First row of above count vector:  [0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Columns Coresponding to above count vector is :
 ['action', 'adventure', 'animation', 'child', 'comedy', 'crime', 'documentary', 'drama', 'fantasy', 'fi', 'film', 'genres', 'horror', 'imax', 'listed', 'musical', 'mystery', 'no', 'noir', 'romance', 'sci', 'thriller', 'war', 'western']


In [10]:
output = movies.loc[:,['movieId','title']]
output = output.join(pd.DataFrame(X))
output

movieId                                title  0  1  2  3  4  5  6  7  \
0            1                     Toy Story (1995)  0  1  1  1  1  0  0  0   
1            2                       Jumanji (1995)  0  1  0  1  0  0  0  0   
2            3              Grumpier Old Men (1995)  0  0  0  0  1  0  0  0   
3            4             Waiting to Exhale (1995)  0  0  0  0  1  0  0  1   
4            5   Father of the Bride Part II (1995)  0  0  0  0  1  0  0  0   
...        ...                                  ... .. .. .. .. .. .. .. ..   
10324   146684        Cosmic Scrat-tastrophe (2015)  0  0  1  1  1  0  0  0   
10325   146878           Le Grand Restaurant (1966)  0  0  0  0  1  0  0  0   
10326   148238       A Very Murray Christmas (2015)  0  0  0  0  1  0  0  0   
10327   148626                 The Big Short (2015)  0  0  0  0  0  0  0  1   
10328   149532  Marco Polo: One Hundred Eyes (2015)  0  0  0  0  0  0  0  0   

       ...  14  15  16  17  18  19  20  21  22  23  
0      ...   0   0   0   0   0   0   0   0   0   0  
1      ...   0   0   0   0   0   0   0   0   0   0  
2      ...   0   0   0   0   0   1   0   0   0   0  
3      ...   0   0   0   0   0   1   0   0   0   0  
4      ...   0   0   0   0   0   0   0   0   0   0  
...    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  
10324  ...   0   0   0   0   0   0   0   0   0   0  
10325  ...   0   0   0   0   0   0   0   0   0   0  
10326  ...   0   0   0   0   0   0   0   0   0   0  
10327  ...   0   0   0   0   0   0   0   0   0   0  
10328  ...   1   0   0   1   0   0   0   0   0   0  

[10329 rows x 26 columns]

In [19]:
#Row corresponds to a movie name
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(X) 
#Each row of matrix coressponds to similarity of a movie with all other movies (row len = 10329)

In [20]:
print(similarities)

[[1.         0.77459667 0.31622777 ... 0.4472136  0.         0.        ]
 [0.77459667 1.         0.         ... 0.         0.         0.        ]
 [0.31622777 0.         1.         ... 0.70710678 0.         0.        ]
 ...
 [0.4472136  0.         0.70710678 ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [21]:
uid = 18 #For user 18 lets recommend movies based on his recent watched movie
time = ratings.loc[ratings["userId"]==uid,["movieId","timestamp"]]
latest_movieId_watched_by_user = time.sort_values(by="timestamp",ascending=False)["movieId"].values[0]
latest_movieId_watched_by_user

8798

In [22]:
movie_index = movies.loc[movies['movieId']==latest_movieId_watched_by_user,["title"]].index[0]
output.loc[output['movieId']==8798,:]

movieId              title  0  1  2  3  4  5  6  7  ...  14  15  16  17  \
5801     8798  Collateral (2004)  1  0  0  0  0  1  0  1  ...   0   0   0   0   

      18  19  20  21  22  23  
5801   0   0   0   1   0   0  

[1 rows x 26 columns]

In [23]:
movie_index,"for movie id",latest_movieId_watched_by_user

(5801, 'for movie id', 8798)

In [24]:
#we need index but we are using id to find which row is crct in similarities matrix
movie_index = movies.loc[movies['movieId']==latest_movieId_watched_by_user,["title"]].index[0]
similarity_values = pd.Series(similarities[movie_index])

In [26]:
#We converted list into series in order to preserve the actual indexes of dataset even after sorting
similarity_values.sort_values(ascending=False)

2906    1.0
7942    1.0
6531    1.0
6530    1.0
7534    1.0
       ... 
4538    0.0
4536    0.0
4533    0.0
4532    0.0
0       0.0
Length: 10329, dtype: float64

In [27]:
similar_movie_indexes = list(similarity_values.sort_values(ascending=False).index)
similar_movie_indexes

[2906,
 7942,
 6531,
 6530,
 7534,
 1269,
 7887,
 9218,
 9372,
 9031,
 10190,
 7718,
 8297,
 2031,
 10203,
 10204,
 8061,
 7085,
 5379,
 6709,
 7095,
 2365,
 5153,
 5540,
 2946,
 6130,
 8076,
 6387,
 9246,
 4586,
 6077,
 8130,
 6864,
 4579,
 7489,
 1259,
 71,
 6615,
 7052,
 10129,
 7262,
 8317,
 5801,
 6117,
 2973,
 258,
 6285,
 6378,
 3821,
 806,
 8533,
 979,
 6520,
 4640,
 6462,
 2303,
 2596,
 6756,
 7115,
 3106,
 309,
 2605,
 5112,
 6959,
 5121,
 2615,
 7989,
 6234,
 9460,
 5092,
 6923,
 5369,
 8425,
 9623,
 122,
 3307,
 4283,
 8610,
 10148,
 4134,
 5826,
 3617,
 8976,
 8267,
 3911,
 1164,
 3233,
 6726,
 9179,
 4503,
 1618,
 19,
 7856,
 3969,
 343,
 7435,
 5411,
 4305,
 7438,
 3508,
 8091,
 3489,
 3625,
 2721,
 9825,
 4430,
 5254,
 600,
 8094,
 125,
 569,
 5963,
 7331,
 1371,
 8459,
 8391,
 6074,
 3515,
 8086,
 6949,
 8992,
 5329,
 9627,
 3483,
 8567,
 10049,
 4674,
 2733,
 1404,
 5777,
 1405,
 8461,
 3205,
 3206,
 7453,
 10039,
 349,
 4681,
 2734,
 9118,
 6350,
 4682,
 9811,
 1316,

In [60]:
#Remove the already watched movie from index list
similar_movie_indexes.remove(movie_index)

In [61]:
def get_movie_by_index(idx):
    return movies_dataset.index[idx]
def get_movie_by_id(mv_id):
    return movies.loc[movies['movieId']==mv_id,['title']].values[0][0]
get_movie_by_index(8899)

'Background to Danger (1943)'

In [62]:
print("Since u watched --->",get_movie_by_id(latest_movieId_watched_by_user),"<--- We recommend you")
for i in range(15):
    print(get_movie_by_index(similar_movie_indexes[i]))

Since u watched ---> Collateral (2004) <--- We recommend you
Magnum Force (1973)
Punisher: War Zone (2008)
Thriller: A Cruel Picture (Thriller - en grym film) (1974)
Violent Cop (Sono otoko, kyôbô ni tsuki) (1989)
Elite Squad (Tropa de Elite) (2007)
Cop Land (1997)
Max Payne (2008)
Rampart (2011)
Get the Gringo (2012)
Hand Gun (1994)
Wild Card (2015)
Taken (2008)
Boondock Saints II: All Saints Day, The (2009)
Corruptor, The (1999)
Run All Night (2015)
